### PR TITLE
Compatibility with Flow 0.17.0.

### PR DESCRIPTION
**Pull request by STRML**
Includes fixes from @RikardLegge's PR #9.

This supersedes #9 and is tested working with all the newest versions of all packages.

For now, we are using the old output format (<= 0.16.0) so that the regex still works. In the future it would be great to use the JSON output but parsing JSON with a regex, which SL requires, feels incorrect.

An example of output I just ran:

### CODE REVIEW

**Comment by nmn** [comment]
+1

**Comment by ckaznocha** [comment]
Hey @STRML thanks for the PR!
Could you please unroll the changes from PR #9, I'm not comfortable with all those changes yet and IMHO it's cleaner to have 1 PR per feature anyway.  Also you'll need to fix the issues that caused the travis build to fail before your changes can be merged.

**Comment by ckaznocha** [comment]
Actually I'm OK with all your changes, can you please just address the issues causing the build to fail and I'll merge this one it.

**Comment by ckaznocha** [comment]
The style issue failing the build doesn't actually look to be caused by your changes. I'll take care of them.

**Pull request merged**
